export default [
  {
    name: 'Screen',
    accepts: ['element', 'inner_element'],
    lastDroppedItem: [
      {
        priviteName: 'Button41',
        backgroundColor: 'blue',
        font_size: 15,
        height: 30,
        left: 106,
        name: 'Button',
        text: 'Button',
        text_align: null,
        text_color: '#000000',
        font_weight: null,
        top: 201,
        type: 'element',
        width: 70,
        screenIndex: 0,
        isSelect: true,
        fontStyle: null,
        textDecoration: null,
        borderColor: '#000000',
        borderWidth: 0,
        borderStyle: 'solid',
        borderRedius: 0,
        hint: null,
        disabled: null,
        keyboard: null,
        src: null,
        resize: null,
        items: null,
        onColor: null,
        offColor: null,
        value: null,
        actions: [
          {
            action: 'click',
            visibility: 'hidden',
            event: 'restful_put',
            route: null,
            params: {
              selectEmail: [
                [
                  '{"name":"Text Input44","screenIndex":0,"index":1,"contain_index":"undefined"}',
                  'title',
                ],
              ],
              selectPassport: null,
              selectTitle: null,
              backgroundColor: null,
              width: null,
              height: null,
              top: null,
              left: null,
              uri: 'https://dummyjson.com/products/1',
              condition: null,
              conditionIndex: null,
            },
          },
        ],
        visibility: true,
        globalStyle: null,
        isChange: true,
      },
      {
        priviteName: 'Text Input44',
        backgroundColor: 'white',
        font_size: 15,
        height: 30,
        left: 77,
        name: 'Text Input',
        text: 'Text Input',
        text_align: null,
        text_color: '#000000',
        font_weight: null,
        top: 113,
        type: 'element',
        width: 111,
        screenIndex: 0,
        isSelect: false,
        fontStyle: null,
        textDecoration: null,
        borderColor: '#000000',
        borderWidth: 1,
        borderStyle: 'solid',
        borderRedius: 0,
        hint: '...',
        disabled: true,
        keyboard: 'text',
        src: null,
        resize: null,
        items: null,
        onColor: null,
        offColor: null,
        value: null,
        actions: [],
        visibility: true,
        globalStyle: null,
        isChange: true,
      },
    ],
    count: 0,
    isSelect: false,
    backgroundColor: '#FFFFFF',
    backgroundImage: null,
  },
  {
    name: 'Screen2',
    accepts: ['element', 'inner_element'],
    lastDroppedItem: [
      {
        priviteName: 'Button43',
        backgroundColor: 'blue',
        font_size: 15,
        height: 30,
        left: 106,
        name: 'Button',
        text: 'Button',
        text_align: null,
        text_color: '#000000',
        font_weight: null,
        top: 94,
        type: 'element',
        width: 70,
        screenIndex: 1,
        isSelect: false,
        fontStyle: null,
        textDecoration: null,
        borderColor: '#000000',
        borderWidth: 0,
        borderStyle: 'solid',
        borderRedius: 0,
        hint: null,
        disabled: null,
        keyboard: null,
        src: null,
        resize: null,
        items: null,
        onColor: null,
        offColor: null,
        value: null,
        actions: [
          {
            action: 'click',
            visibility: 'hidden',
            event: 'navigate_back',
            route: null,
            params: {
              selectEmail: null,
              selectPassport: null,
              selectTitle: null,
              selectCostum: null,
              backgroundColor: null,
              width: null,
              height: null,
              top: null,
              left: null,
              uri: null,
              condition: null,
              conditionIndex: null,
            },
          },
        ],
        visibility: true,
        globalStyle: null,
      },
    ],
    isSelect: false,
    backgroundColor: '#FFFFFF',
    backgroundImage:
      'https://www.klasiksanatlar.com/img/sayfalar/b/1_1598452306_resim.png',
  },
];
